### ISSUE TITLE
Show main window via the tray icon when window was minimized

### ISSUE THREAD

**Issue by mipastgt** [dlemmermann/jfxcentral#21]
When the user has minimized the main window it should be possible to show it again via the tray icon. I have checked some other applications and they all show the main window (if they have a main window) when you click on the tray icon. JFX-Central only shows the menu instead which, to my opion, does not correspond to the users expectation in this case.

Maybe one should also move the "Exit Application" to the end of the menu list and add a separator. That's the place where you normally expect the option to terminate the application.

**Comment by dlemmermann** [comment]
Good point. I will add this item. The "exit app" item for some reason is automatically placed by FXTray. Not sure why it behaves like that.

**Comment by dlemmermann** [comment]
Done.
